version: '3.7'

services:
  db:
    container_name: db_test
    image: postgres:13.1
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: test
    ports:
      - 5432:5432
    restart: always
